### PR TITLE
Add logref and path

### PR DESCRIPTION
**Pull request by WidoBurg**

### CODE REVIEW

**Comment by WidoBurg** [comment]
@jcassee @mvcatsifma please have a look at this PR

**Comment by mvcatsifma** [comment]
Wat mij betreft OK.

**Comment by jcassee** [comment]
Looks good, merging!

**Comment by jcassee** [comment]
Released as 0.7.0.

**Comment by WidoBurg** [comment]
dist/hypermedia.js was not yet updated for 0.7.0. 

Will you release again with an updated dist?

greetings
Wido

**Comment by jcassee** [comment]
Awkward! Release 0.7.1 to fix this.

**Pull request merged**
